# Attempting to write an octree in python

I want this to work with VERY large data sets that can't be stored fully in memory.  So my procedure will be as follows:
- need to read in line-by-line and clear memory every X MB (or maybe every X particles;can I check memory load in python?)
- go down to nodes with containing N particles
- need to write out tree with node sizes and centers and also ending nodes with actual particles

I will work in the octreeStream.py file.  This is working, though once it has to start reading and writing lots of files, it becomes VERY slow (setting NMemoryMax to be as large as possible will speed things up).

The ultimate goal is to use this within Firefly.  First I create the python code.  Then I will create a simple WebGL utility to use it (hopefully showing more Gaia data than it can handle w/o the octree).  Then we will work on incorporating this into Firefly.

In [2]:
%load_ext autoreload
%autoreload 2

from octreeStream import octreeStream

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [7]:
#I'll use a Gaia data set.  I've already compiled this one from DR2.  For production, I'd want to recompile from EDR3
# WORK/Gaia/GaiaCompiled_RV_TAP.txt
# for some reason this is a space-separated and not comma-separated, but here are the colummns
# 'x', 'y', 'z', 'vx', 'vy', 'vz', 'teff_val', 'phot_g_mean_mag', 'flag'
# I believe flag == 1 if there is no RV; for now all I care about is the x,y,z, position

o = octreeStream('/Users/ageller/WORK/Gaia/GaiaCompiled_RV_TAP.txt', delim = ' ', 
                 NNodeMax = 50000, NMemoryMax = 3e6, Nmax=1e5, verbose=1, minWidth=0.1,
                 path='/Users/ageller/VISUALIZATIONS/octree_threejs_Gaia/WebGL_octreePartition/src/data/junk')

files will be output to: C:\Users\ageller\VISUALIZATIONS\octree_threejs_Gaia\WebGL_octreePartition\src\data\junk


In [8]:
o.compileOctree()

have initial center and size [ -457.4696629   -433.66704784 -1039.13279431] 15557.616459301153
line :  10000
line :  20000
line :  30000
line :  40000
creating child nodes 0 0 50000 15557.616459301153
line :  50000
creating child nodes 1 0_1 50000 7778.808229650576
creating child nodes 16 0_1_8 50000 3889.404114825288
creating child nodes 24 0_1_8_8 50000 1944.702057412644
line :  60000
line :  70000
line :  80000
creating child nodes 28 0_1_8_8_4 50000 972.351028706322
line :  90000
line :  100000
dumping nodes to files ...
randomizing particle order in data files ... 
done


In [9]:
o.checkNodeFiles()

Number of bad files =  0
maximum number of particles in a file =  28960
minimum number of particles in a file =  3


In [10]:
#o.populateAllNodesFromFiles()

Populated octree from files.
 -- total number of particles =  100000
 -- total number of nodes =  41
 -- total number of base nodes =  30


## Testing with hdf5 files

In [172]:
o = octreeStream('/Users/ageller/VISUALIZATIONS/FIREdata/m12i_res7100/snapdir_600/snapshot_600.0.hdf5', 
                 h5keyList = ['PartType0', 'Coordinates'],
                 NNodeMax = 50000, NMemoryMax = 5e6, Nmax=1e9, verbose=1, minWidth=1e-4,
                 path='/Users/ageller/VISUALIZATIONS/octree_threejs_Gaia/WebGL_octreePartition/src/data/m12i_res71000/octreeNodes')

files will be output to: C:\Users\ageller\VISUALIZATIONS\octree_threejs_Gaia\WebGL_octreePartition\src\data\m12i_res71000\octreeNodes


In [ ]:
o.compileOctree()

calculating center and size ... 
have initial center and size [29367.70125147 31128.80508096 32527.27650095] 15612.77387281969
line :  10000
line :  20000
line :  30000
line :  40000
creating child nodes 0 50000 15612.77387281969
   Child node, Nparticles 01 0
      checking node...
      width =  7806.386936409845
      Nparticles =  0
      center =  [33270.8947196729, 35031.99854916264, 36430.469969154794]
   Child node, Nparticles 02 0
      checking node...
      width =  7806.386936409845
      Nparticles =  0
      center =  [25464.507783263056, 35031.99854916264, 36430.469969154794]
   Child node, Nparticles 03 9347
      checking node...
      width =  7806.386936409845
      Nparticles =  9347
      center =  [33270.8947196729, 27225.6116127528, 36430.469969154794]
      mean particle position =  [29387.24188553 30854.72203929 32613.19768666]
      max particle position =  [29413.43800212 30879.76142461 32639.35967162]
      min particle position =  [29367.70535738 30821.1283

line :  140000
line :  150000
line :  160000
line :  170000
creating child nodes 07221 50000 975.7983670512306
   Child node, Nparticles 072211 7259
      checking node...
      width =  487.8991835256153
      Nparticles =  7259
      center =  [31075.34839380763, 30884.855489194917, 32283.326909187064]
      mean particle position =  [31031.10865126 30786.52892178 32210.78795394]
      max particle position =  [31319.1739174  31127.61078608 32346.04659116]
      min particle position =  [30831.4096472  30640.90720136 32039.56581056]
      max distance for particle positions =  [487.76427019 486.70358472 306.4807806 ]
      width of particles 402.0984738809575 -0.1132230164585053
   Child node, Nparticles 072212 14749
      checking node...
      width =  487.8991835256153
      Nparticles =  14749
      center =  [30587.449210282015, 30884.855489194917, 32283.326909187064]
      mean particle position =  [30637.0075274  30803.89913378 32193.72847799]
      max particle position =  [3

   Child node, Nparticles 07222221 0
      checking node...
      width =  121.97479588140382
      Nparticles =  0
      center =  [29550.66344529008, 31067.817683017023, 32466.28910300917]
   Child node, Nparticles 07222222 0
      checking node...
      width =  121.97479588140382
      Nparticles =  0
      center =  [29428.688649408676, 31067.817683017023, 32466.28910300917]
   Child node, Nparticles 07222223 0
      checking node...
      width =  121.97479588140382
      Nparticles =  0
      center =  [29550.66344529008, 30945.84288713562, 32466.28910300917]
   Child node, Nparticles 07222224 50002
      checking node...
      width =  121.97479588140382
      Nparticles =  50002
      center =  [29428.688649408676, 30945.84288713562, 32466.28910300917]
      mean particle position =  [29398.49911495 30971.12025126 32476.86015774]
      max particle position =  [29413.43253388 30989.72499148 32522.05366775]
      min particle position =  [29376.78390943 30938.42108634 32463.419

line :  240000
line :  250000
creating child nodes 06 50000 7806.386936409845
   Child node, Nparticles 061 0
      checking node...
      width =  3903.1934682049223
      Nparticles =  0
      center =  [27416.10451736552, 36983.5952832651, 30575.67976684741]
   Child node, Nparticles 062 0
      checking node...
      width =  3903.1934682049223
      Nparticles =  0
      center =  [23512.911049160593, 36983.5952832651, 30575.67976684741]
   Child node, Nparticles 063 50000
      checking node...
      width =  3903.1934682049223
      Nparticles =  50000
      center =  [27416.10451736552, 33080.401815060184, 30575.67976684741]
      mean particle position =  [28098.92226012 31864.58500765 32266.05478302]
      max particle position =  [28680.27021452 32346.06575824 32463.40287863]
      min particle position =  [27653.88113408 31407.6375823  32111.49074721]
      max distance for particle positions =  [1026.38908044  938.42817594  351.91213142]
      width of particles 2489.75439

   Child node, Nparticles 0181 0
      checking node...
      width =  1951.5967341024611
      Nparticles =  0
      center =  [32295.096352621666, 34056.20018211142, 35454.67160210357]
   Child node, Nparticles 0182 0
      checking node...
      width =  1951.5967341024611
      Nparticles =  0
      center =  [30343.499618519207, 34056.20018211142, 35454.67160210357]
   Child node, Nparticles 0183 0
      checking node...
      width =  1951.5967341024611
      Nparticles =  0
      center =  [32295.096352621666, 32104.603448008955, 35454.67160210357]
   Child node, Nparticles 0184 0
      checking node...
      width =  1951.5967341024611
      Nparticles =  0
      center =  [30343.499618519207, 32104.603448008955, 35454.67160210357]
   Child node, Nparticles 0185 0
      checking node...
      width =  1951.5967341024611
      Nparticles =  0
      center =  [32295.096352621666, 34056.20018211142, 33503.0748680011]
   Child node, Nparticles 0186 0
      checking node...
      wi

   Child node, Nparticles 03661 0
      checking node...
      width =  975.7983670512306
      Nparticles =  0
      center =  [30831.398802044823, 30640.90589743211, 33990.97405152672]
   Child node, Nparticles 03662 963
      checking node...
      width =  975.7983670512306
      Nparticles =  963
      center =  [29855.60043499359, 30640.90589743211, 33990.97405152672]
      mean particle position =  [30067.81095747 30846.5187171  33593.49848724]
      max particle position =  [30280.3796907  31127.43173618 33753.66050631]
      min particle position =  [29999.99030367 30194.50375082 33503.0774084 ]
      max distance for particle positions =  [280.38938703 932.92798536 250.5830979 ]
      width of particles 749.4696301410202 569.1691243828172
   Child node, Nparticles 03663 0
      checking node...
      width =  975.7983670512306
      Nparticles =  0
      center =  [30831.398802044823, 29665.107530380876, 33990.97405152672]
   Child node, Nparticles 03664 4
      checking node

line :  440000
line :  450000
line :  460000
line :  470000
line :  480000
creating child nodes 08 50000 7806.386936409845
   Child node, Nparticles 081 50000
      checking node...
      width =  3903.1934682049223
      Nparticles =  50000
      center =  [27416.10451736552, 29177.208346855263, 30575.67976684741]
      mean particle position =  [28781.73533739 30753.75856829 31960.67274086]
      max particle position =  [29367.70099297 31085.04340306 32522.05156487]
      min particle position =  [28357.70699377 30527.84921954 31642.27678791]
      max distance for particle positions =  [1009.9939992   557.19418352  879.77477696]
      width of particles 3334.577187291555 3258.475928884942
   Child node, Nparticles 082 0
      checking node...
      width =  3903.1934682049223
      Nparticles =  0
      center =  [23512.911049160593, 29177.208346855263, 30575.67976684741]
   Child node, Nparticles 083 0
      checking node...
      width =  3903.1934682049223
      Nparticles =  0


line :  500000
line :  510000
line :  520000
line :  530000
creating child nodes 04 50000 7806.386936409845
   Child node, Nparticles 041 0
      checking node...
      width =  3903.1934682049223
      Nparticles =  0
      center =  [27416.10451736552, 29177.208346855263, 38382.06670325725]
   Child node, Nparticles 042 0
      checking node...
      width =  3903.1934682049223
      Nparticles =  0
      center =  [23512.911049160593, 29177.208346855263, 38382.06670325725]
   Child node, Nparticles 043 0
      checking node...
      width =  3903.1934682049223
      Nparticles =  0
      center =  [27416.10451736552, 25274.014878650338, 38382.06670325725]
   Child node, Nparticles 044 0
      checking node...
      width =  3903.1934682049223
      Nparticles =  0
      center =  [23512.911049160593, 25274.014878650338, 38382.06670325725]
   Child node, Nparticles 045 50000
      checking node...
      width =  3903.1934682049223
      Nparticles =  50000
      center =  [27416.1045

line :  540000
line :  550000
line :  560000
line :  570000
line :  580000
creating child nodes 018861 50000 487.8991835256153
   Child node, Nparticles 0188611 0
      checking node...
      width =  243.94959176280764
      Nparticles =  0
      center =  [30221.524822637803, 32958.42701917878, 33381.1000721197]
   Child node, Nparticles 0188612 0
      checking node...
      width =  243.94959176280764
      Nparticles =  0
      center =  [29977.575230874994, 32958.42701917878, 33381.1000721197]
   Child node, Nparticles 0188613 0
      checking node...
      width =  243.94959176280764
      Nparticles =  0
      center =  [30221.524822637803, 32714.47742741597, 33381.1000721197]
   Child node, Nparticles 0188614 0
      checking node...
      width =  243.94959176280764
      Nparticles =  0
      center =  [29977.575230874994, 32714.47742741597, 33381.1000721197]
   Child node, Nparticles 0188615 1644
      checking node...
      width =  243.94959176280764
      Nparticles =  1

line :  650000
line :  660000
line :  670000
line :  680000
line :  690000
line :  700000
line :  710000
line :  720000
line :  730000
line :  740000
line :  750000
line :  760000
creating child nodes 01888 50000 975.7983670512306
   Child node, Nparticles 018881 0
      checking node...
      width =  487.8991835256153
      Nparticles =  0
      center =  [30099.5500267564, 31860.653856246146, 33259.125276238294]
   Child node, Nparticles 018882 0
      checking node...
      width =  487.8991835256153
      Nparticles =  0
      center =  [29611.650843230782, 31860.653856246146, 33259.125276238294]
   Child node, Nparticles 018883 3469
      checking node...
      width =  487.8991835256153
      Nparticles =  3469
      center =  [30099.5500267564, 31372.75467272053, 33259.125276238294]
      mean particle position =  [30129.25774686 31223.21849384 33262.03700933]
      max particle position =  [30343.49598797 31407.59251831 33503.03782678]
      min particle position =  [29999.995

line :  1020000
line :  1030000
line :  1040000
line :  1050000
line :  1060000
line :  1070000
creating child nodes 06334 50000 975.7983670512306
   Child node, Nparticles 063341 1913
      checking node...
      width =  487.8991835256153
      Nparticles =  1913
      center =  [28147.95329265394, 31860.653856246146, 32283.326909187064]
      mean particle position =  [28142.99579856 31659.23887914 32128.00797494]
      max particle position =  [28356.29213151 31873.85009221 32345.43367568]
      min particle position =  [27904.1275843  31616.77694994 32039.42901741]
      max distance for particle positions =  [452.16454721 257.07314227 306.00465827]
      width of particles 388.2854643758566 -35.486869499975
   Child node, Nparticles 063342 19509
      checking node...
      width =  487.8991835256153
      Nparticles =  19509
      center =  [27660.054109128323, 31860.653856246146, 32283.326909187064]
      mean particle position =  [27811.97216501 31789.33080516 32182.97515164]


line :  1150000
line :  1160000
line :  1170000
line :  1180000
line :  1190000
line :  1200000
line :  1210000
line :  1220000
line :  1230000
line :  1240000
creating child nodes 02777 50000 975.7983670512306
   Child node, Nparticles 027771 0
      checking node...
      width =  487.8991835256153
      Nparticles =  0
      center =  [29123.751659705173, 31860.653856246146, 33259.125276238294]
   Child node, Nparticles 027772 0
      checking node...
      width =  487.8991835256153
      Nparticles =  0
      center =  [28635.852476179556, 31860.653856246146, 33259.125276238294]
   Child node, Nparticles 027773 3099
      checking node...
      width =  487.8991835256153
      Nparticles =  3099
      center =  [29123.751659705173, 31372.75467272053, 33259.125276238294]
      mean particle position =  [29330.15313242 31254.04989705 33032.21707738]
      max particle position =  [29367.69002658 31348.72803116 33049.92547002]
      min particle position =  [29296.13581484 31173.0733

line :  1300000
line :  1310000
creating child nodes 0722224 50000 243.94959176280764
   Child node, Nparticles 07222241 20954
      checking node...
      width =  121.97479588140382
      Nparticles =  20954
      center =  [29550.66344529008, 30823.868091254215, 32466.28910300917]
      mean particle position =  [29507.24843047 30859.95684061 32507.65611319]
      max particle position =  [29530.74320738 30884.85156831 32527.27260954]
      min particle position =  [29489.67659131 30821.11497811 32463.4092158 ]
      max distance for particle positions =  [41.06661607 63.73659021 63.86339374]
      width of particles 102.15235873755036 58.23036390915149
   Child node, Nparticles 07222242 12015
      checking node...
      width =  121.97479588140382
      Nparticles =  12015
      center =  [29428.688649408676, 30823.868091254215, 32466.28910300917]
      mean particle position =  [29481.09244504 30862.99364008 32505.27281031]
      max particle position =  [29489.67380227 30884.853

line :  1380000
line :  1390000
line :  1400000
creating child nodes 0811113 50000 243.94959176280764
   Child node, Nparticles 08111131 18172
      checking node...
      width =  121.97479588140382
      Nparticles =  18172
      center =  [29306.71385352728, 30823.868091254215, 32466.28910300917]
      mean particle position =  [29327.77812435 30850.72178055 32491.33666849]
      max particle position =  [29354.78602104 30879.76040872 32522.04600296]
      min particle position =  [29266.81082061 30821.11177136 32463.41174086]
      max distance for particle positions =  [87.97520043 58.64863736 58.63426211]
      width of particles 90.4273075127339 53.13599757560951
   Child node, Nparticles 08111132 3387
      checking node...
      width =  121.97479588140382
      Nparticles =  3387
      center =  [29184.739057645875, 30823.868091254215, 32466.28910300917]
      mean particle position =  [29210.07470601 30790.75523575 32437.35883371]
      max particle position =  [29237.468738

line :  1460000
line :  1470000
line :  1480000
line :  1490000
line :  1500000
line :  1510000
creating child nodes 081116 50000 487.8991835256153
   Child node, Nparticles 0811161 8721
      checking node...
      width =  243.94959176280764
      Nparticles =  8721
      center =  [28757.82727206096, 31006.83028507632, 31917.402521542852]
      mean particle position =  [28727.45261963 30986.97165647 32004.78527324]
      max particle position =  [28826.9017877  31128.79683132 32039.37261103]
      min particle position =  [28635.85284942 30884.85788264 31876.94525021]
      max distance for particle positions =  [191.04893828 243.93894868 162.42736083]
      width of particles 208.68211343615096 81.5128181551263
   Child node, Nparticles 0811162 2025
      checking node...
      width =  243.94959176280764
      Nparticles =  2025
      center =  [28513.877680298152, 31006.83028507632, 31917.402521542852]
      mean particle position =  [28613.49888502 31015.63622808 32021.09649222

line :  1600000
line :  1610000
line :  1620000
line :  1630000
line :  1640000
line :  1650000
line :  1660000
line :  1670000
line :  1680000
line :  1690000
line :  1700000
line :  1710000
line :  1720000
line :  1730000
line :  1740000
line :  1750000
line :  1760000
line :  1770000
line :  1780000
line :  1790000
line :  1800000
line :  1810000
line :  1820000
line :  1830000
line :  1840000
line :  1850000
line :  1860000
line :  1870000
line :  1880000
line :  1890000
line :  1900000
creating child nodes 0811125 50000 243.94959176280764
   Child node, Nparticles 08111251 4640
      checking node...
      width =  121.97479588140382
      Nparticles =  4640
      center =  [28818.814670001662, 31067.817683017023, 32222.339511246362]
      mean particle position =  [28792.4249434  31092.47708653 32192.64344674]
      max particle position =  [28826.91535984 31128.7552954  32228.76550797]
      min particle position =  [28757.84889657 31006.89183918 32161.37432315]
      max distan

line :  1950000
line :  1960000
line :  1970000
creating child nodes 072224 50000 487.8991835256153
   Child node, Nparticles 0722241 0
      checking node...
      width =  243.94959176280764
      Nparticles =  0
      center =  [29733.625639112186, 30518.931101550705, 32405.30170506847]
   Child node, Nparticles 0722242 13927
      checking node...
      width =  243.94959176280764
      Nparticles =  13927
      center =  [29489.676047349378, 30518.931101550705, 32405.30170506847]
      mean particle position =  [29429.94444972 30434.70007458 32406.82884702]
      max particle position =  [29472.08761058 30469.18992352 32463.3982166 ]
      min particle position =  [29367.70438187 30396.9596904  32346.10452704]
      max distance for particle positions =  [104.38322871  72.23023312 117.29368955]
      width of particles 178.63376538445314 -1.1006664939632174
   Child node, Nparticles 0722243 0
      checking node...
      width =  243.94959176280764
      Nparticles =  0
      cent

line :  2200000
line :  2210000
line :  2220000
line :  2230000
line :  2240000
line :  2250000
line :  2260000
line :  2270000
line :  2280000
line :  2290000
line :  2300000
line :  2310000
line :  2320000
line :  2330000
line :  2340000
line :  2350000
line :  2360000
line :  2370000
line :  2380000
line :  2390000
line :  2400000
line :  2410000
line :  2420000
line :  2430000
creating child nodes 018868 50000 487.8991835256153
   Child node, Nparticles 0188681 11067
      checking node...
      width =  243.94959176280764
      Nparticles =  11067
      center =  [29733.625639112186, 32470.527835653167, 32893.20088859408]
      mean particle position =  [29740.21096801 32559.7492095  32932.63380552]
      max particle position =  [29765.34649311 32592.49926896 33015.17079139]
      min particle position =  [29677.42170376 32522.0368372  32873.98755279]
      max distance for particle positions =  [ 87.92478936  70.46243176 141.1832386 ]
      width of particles 172.48406884661196 

line :  2500000
line :  2510000
creating child nodes 07224 50000 975.7983670512306
   Child node, Nparticles 072241 0
      checking node...
      width =  487.8991835256153
      Nparticles =  0
      center =  [30099.5500267564, 29909.057122143684, 32283.326909187064]
   Child node, Nparticles 072242 17099
      checking node...
      width =  487.8991835256153
      Nparticles =  17099
      center =  [29611.650843230782, 29909.057122143684, 32283.326909187064]
      mean particle position =  [29478.72811854 29949.58540793 32341.60105858]
      max particle position =  [29530.73534194 30152.9992054  32368.09330767]
      min particle position =  [29413.52211747 29875.34266547 32228.83664336]
      max distance for particle positions =  [117.21322447 277.65653993 139.25666431]
      width of particles 317.73728074921524 210.2276265899054
   Child node, Nparticles 072243 1279
      checking node...
      width =  487.8991835256153
      Nparticles =  1279
      center =  [30099.550026

line :  2820000
line :  2830000
creating child nodes 06331 50000 975.7983670512306
   Child node, Nparticles 063311 0
      checking node...
      width =  487.8991835256153
      Nparticles =  0
      center =  [29123.751659705173, 32836.452223297376, 32283.326909187064]
   Child node, Nparticles 063312 0
      checking node...
      width =  487.8991835256153
      Nparticles =  0
      center =  [28635.852476179556, 32836.452223297376, 32283.326909187064]
   Child node, Nparticles 063313 3013
      checking node...
      width =  487.8991835256153
      Nparticles =  3013
      center =  [29123.751659705173, 32348.553039771763, 32283.326909187064]
      mean particle position =  [29047.62435476 32138.22338686 32432.61305334]
      max particle position =  [29367.68396109 32344.29492312 32527.25730023]
      min particle position =  [28879.86783934 32104.60805136 32346.18713943]
      max distance for particle positions =  [487.81612175 239.68687176 181.0701608 ]
      width of parti

line :  3070000
line :  3080000
line :  3090000
line :  3100000
line :  3110000
line :  3120000
line :  3130000
line :  3140000
creating child nodes 0722222428 50000 30.493698970350955
   Child node, Nparticles 07222224281 0
      checking node...
      width =  15.246849485175478
      Nparticles =  0
      center =  [29390.57152569574, 30968.713161363383, 32489.159377236934]
   Child node, Nparticles 07222224282 51
      checking node...
      width =  15.246849485175478
      Nparticles =  51
      center =  [29375.324676210563, 30968.713161363383, 32489.159377236934]
      mean particle position =  [29378.72520601 30975.67126009 32490.88083772]
      max particle position =  [29380.33639785 30976.22263078 32492.68677489]
      min particle position =  [29376.78415228 30975.17255698 32489.06472958]
      max distance for particle positions =  [3.55224557 1.0500738  3.62204531]
      width of particles 9.258602258285062 13.9688650404496
   Child node, Nparticles 07222224283 0
      c

line :  3200000
line :  3210000
line :  3220000
line :  3230000
line :  3240000
line :  3250000
line :  3260000
line :  3270000
line :  3280000
line :  3290000
line :  3300000
line :  3310000
creating child nodes 027775 50000 487.8991835256153
   Child node, Nparticles 0277751 0
      checking node...
      width =  243.94959176280764
      Nparticles =  0
      center =  [29245.726455586577, 31982.62865212755, 32893.20088859408]
   Child node, Nparticles 0277752 0
      checking node...
      width =  243.94959176280764
      Nparticles =  0
      center =  [29001.77686382377, 31982.62865212755, 32893.20088859408]
   Child node, Nparticles 0277753 28892
      checking node...
      width =  243.94959176280764
      Nparticles =  28892
      center =  [29245.726455586577, 31738.679060364742, 32893.20088859408]
      mean particle position =  [29183.59010112 31673.47596835 32870.70524432]
      max particle position =  [29296.11102981 31759.51882296 32932.61870929]
      min particle po

line :  3380000
line :  3390000
line :  3400000
line :  3410000
line :  3420000
line :  3430000
line :  3440000
creating child nodes 063314 50000 487.8991835256153
   Child node, Nparticles 0633141 0
      checking node...
      width =  243.94959176280764
      Nparticles =  0
      center =  [28757.82727206096, 32470.527835653167, 32405.30170506847]
   Child node, Nparticles 0633142 0
      checking node...
      width =  243.94959176280764
      Nparticles =  0
      center =  [28513.877680298152, 32470.527835653167, 32405.30170506847]
   Child node, Nparticles 0633143 41896
      checking node...
      width =  243.94959176280764
      Nparticles =  41896
      center =  [28757.82727206096, 32226.57824389036, 32405.30170506847]
      mean particle position =  [28706.7907845  32265.06199666 32437.55339053]
      max particle position =  [28879.7905714  32346.06988831 32527.23870001]
      min particle position =  [28635.85280063 32104.60350219 32346.11729901]
      max distance for 

line :  3610000
line :  3620000
line :  3630000
line :  3640000
line :  3650000
line :  3660000
line :  3670000
line :  3680000
creating child nodes 07222224276 50000 15.246849485175478
   Child node, Nparticles 072222242761 44
      checking node...
      width =  7.623424742587739
      Nparticles =  44
      center =  [29409.630087552207, 30972.524873734677, 32477.72424012305]
      mean particle position =  [29406.59565967 30972.99288085 32474.15765876]
      max particle position =  [29409.35620191 30976.20102626 32474.39676982]
      min particle position =  [29405.81903086 30971.51721068 32473.92420442]
      max distance for particle positions =  [3.53717105 4.68381558 0.4725654 ]
      width of particles 5.362092896300114 2.6684894696081756
   Child node, Nparticles 072222242762 410
      checking node...
      width =  7.623424742587739
      Nparticles =  410
      center =  [29402.006662809617, 30972.524873734677, 32477.72424012305]
      mean particle position =  [29402.85

line :  3860000
line :  3870000
line :  3880000
line :  3890000
creating child nodes 0722242 50000 243.94959176280764
   Child node, Nparticles 07222421 474
      checking node...
      width =  121.97479588140382
      Nparticles =  474
      center =  [29550.66344529008, 30579.918499491407, 32466.28910300917]
      mean particle position =  [29504.66994754 30523.2940362  32425.80453562]
      max particle position =  [29530.3984694  30527.83493143 32463.30226298]
      min particle position =  [29489.68493666 30518.94314396 32405.36870514]
      max distance for particle positions =  [40.71353274  8.89178747 57.93355783]
      width of particles 104.42973859439454 -63.90723790248376
   Child node, Nparticles 07222422 13917
      checking node...
      width =  121.97479588140382
      Nparticles =  13917
      center =  [29428.688649408676, 30579.918499491407, 32466.28910300917]
      mean particle position =  [29448.03055996 30552.99779804 32434.00401656]
      max particle position

line :  4160000
line :  4170000
line :  4180000
line :  4190000
line :  4200000
line :  4210000
line :  4220000
line :  4230000
line :  4240000
creating child nodes 08112 50000 975.7983670512306
   Child node, Nparticles 081121 9212
      checking node...
      width =  487.8991835256153
      Nparticles =  9212
      center =  [28147.95329265394, 30884.855489194917, 32283.326909187064]
      mean particle position =  [28299.18450419 31035.92478447 32197.18350948]
      max particle position =  [28391.90234509 31128.79562396 32346.0241473 ]
      min particle position =  [28123.11784582 30938.44546107 32111.50345411]
      max distance for particle positions =  [268.78449926 190.35016289 234.52069318]
      width of particles 381.0755773106768 297.5301066368156
   Child node, Nparticles 081122 0
      checking node...
      width =  487.8991835256153
      Nparticles =  0
      center =  [27660.054109128323, 30884.855489194917, 32283.326909187064]
   Child node, Nparticles 081123 0
   

line :  4310000
line :  4320000
line :  4330000
creating child nodes 0811186 50000 243.94959176280764
   Child node, Nparticles 08111861 13087
      checking node...
      width =  121.97479588140382
      Nparticles =  13087
      center =  [28574.865078238854, 30579.918499491407, 31734.440327720746]
      mean particle position =  [28551.29680567 30578.7387181  31738.21309399]
      max particle position =  [28592.29993915 30640.87697461 31795.41659195]
      min particle position =  [28513.87813046 30518.97899771 31673.46459931]
      max distance for particle positions =  [ 78.42180869 121.8979769  121.95199263]
      width of particles 104.10221057606614 0.018973344362166245
   Child node, Nparticles 08111862 11214
      checking node...
      width =  121.97479588140382
      Nparticles =  11214
      center =  [28452.89028235745, 30579.918499491407, 31734.440327720746]
      mean particle position =  [28474.35997865 30576.09354389 31721.876014  ]
      max particle position =  [

line :  4440000
line :  4450000
line :  4460000
line :  4470000
line :  4480000
line :  4490000
creating child nodes 07222224285 50000 15.246849485175478
   Child node, Nparticles 072222242851 4031
      checking node...
      width =  7.623424742587739
      Nparticles =  4031
      center =  [29394.383238067036, 30972.524873734677, 32477.72424012305]
      mean particle position =  [29392.41859848 30972.98517696 32474.80986068]
      max particle position =  [29398.19113928 30976.26878726 32478.06499645]
      min particle position =  [29390.57259799 30968.71595077 32473.91269268]
      max distance for particle positions =  [7.61854129 7.55283648 4.15230377]
      width of particles 5.855949811023524 -0.002738866587606026
   Child node, Nparticles 072222242852 13721
      checking node...
      width =  7.623424742587739
      Nparticles =  13721
      center =  [29386.759813324446, 30972.524873734677, 32477.72424012305]
      mean particle position =  [29389.33538463 30972.64774791

line :  4550000
line :  4560000
line :  4570000
line :  4580000
line :  4590000
line :  4600000
line :  4610000
line :  4620000
creating child nodes 072222243 50000 60.98739794070191
   Child node, Nparticles 0722222431 5330
      checking node...
      width =  30.493698970350955
      Nparticles =  5330
      center =  [29474.4291978642, 30930.596037650444, 32512.029651464694]
      mean particle position =  [29480.82624857 30927.2348306  32509.28562423]
      max particle position =  [29489.6754757  30938.41398737 32527.25914186]
      min particle position =  [29472.09654579 30915.35293207 32496.78280995]
      max distance for particle positions =  [17.57892991 23.06105531 30.47633192]
      width of particles 25.23395677658987 12.913625761262665
   Child node, Nparticles 0722222432 10099
      checking node...
      width =  30.493698970350955
      Nparticles =  10099
      center =  [29443.93549889385, 30930.596037650444, 32512.029651464694]
      mean particle position =  [294

line :  4670000
creating child nodes 0277773 50000 243.94959176280764
   Child node, Nparticles 02777731 14302
      checking node...
      width =  121.97479588140382
      Nparticles =  14302
      center =  [29306.71385352728, 31311.767274779828, 32954.18828653478]
      mean particle position =  [29328.83530254 31320.90083358 32945.71022296]
      max particle position =  [29367.69941237 31372.75382305 33015.12709218]
      min particle position =  [29296.14586455 31250.78129111 32893.2194393 ]
      max distance for particle positions =  [ 71.55354782 121.97253194 121.90765288]
      width of particles 102.88131844047139 50.417569861150696
   Child node, Nparticles 02777732 1008
      checking node...
      width =  121.97479588140382
      Nparticles =  1008
      center =  [29184.739057645875, 31311.767274779828, 32954.18828653478]
      mean particle position =  [29210.86252911 31263.02178771 32965.55209709]
      max particle position =  [29237.47979218 31290.21292668 32991.26

line :  4690000
line :  4700000
line :  4710000
line :  4720000
line :  4730000
line :  4740000
line :  4750000
line :  4760000
line :  4770000
line :  4780000
line :  4790000
line :  4800000
line :  4810000
line :  4820000
line :  4830000
line :  4840000
line :  4850000
creating child nodes 081125 50000 487.8991835256153
   Child node, Nparticles 0811251 0
      checking node...
      width =  243.94959176280764
      Nparticles =  0
      center =  [28269.928088535344, 31006.83028507632, 31917.402521542852]
   Child node, Nparticles 0811252 0
      checking node...
      width =  243.94959176280764
      Nparticles =  0
      center =  [28025.978496772535, 31006.83028507632, 31917.402521542852]
   Child node, Nparticles 0811253 18558
      checking node...
      width =  243.94959176280764
      Nparticles =  18558
      center =  [28269.928088535344, 30762.880693313513, 31917.402521542852]
      mean particle position =  [28180.26870515 30729.84018863 31897.34895918]
      max parti

In [ ]:
o.compileOctree(inputFile='/Users/ageller/VISUALIZATIONS/FIREdata/m12i_res7100/snapdir_600/snapshot_600.1.hdf5', append=True)

In [ ]:
o.compileOctree(inputFile='/Users/ageller/VISUALIZATIONS/FIREdata/m12i_res7100/snapdir_600/snapshot_600.2.hdf5', append=True)

In [ ]:
o.compileOctree(inputFile='/Users/ageller/VISUALIZATIONS/FIREdata/m12i_res7100/snapdir_600/snapshot_600.3.hdf5', append=True)

In [ ]:
o.checkNodeFiles()

In [ ]:
#o.populateAllNodesFromFiles()

In [100]:
o.checkNodeParticles(iden='0722222468888888888888888888')

checking node...
width =  0.00011632423008098967
center =  [29367.70130963009, 30945.842945297733, 32405.301763230585]
mean particle position =  [28117.75403463 29846.04872256 31358.68751193]
max particle position =  [29002.849053   30850.33039364 32111.48087621]
min particle position =  [28005.81009505 29706.78577699 31173.12291594]
max distance for particle positions =  [ 997.03895795 1143.54461666  938.35796027]


In [101]:
import numpy as np

In [105]:
for i,n in enumerate(o.nodes):
    if (i == 0):
        allPositions = np.array([[n['x'], n['y'], n['z']]])
    else:
        allPositions = np.append(allPositions, [[n['x'], n['y'], n['z']]], axis=0)
print(allPositions)

[[29367.70125147 31128.80508096 32527.27650095]
 [33270.89471967 35031.99854916 36430.46996915]
 [25464.50778326 35031.99854916 36430.46996915]
 ...
 [29367.70130963 30884.85566368 32496.78286014]
 [29367.70142595 30884.85554736 32496.78286014]
 [29367.70130963 30884.85554736 32496.78286014]]


In [104]:
o.baseNodePositions

array([[33270.89471967, 27225.61161275, 36430.46996915],
       [25464.50778326, 27225.61161275, 36430.46996915],
       [32295.09635262, 30153.00671391, 31551.4781339 ],
       [31075.34839381, 30396.95630567, 32283.32690919],
       [31075.34839381, 30396.95630567, 31795.42772566],
       [31075.34839381, 30884.85548919, 31795.42772566],
       [31075.34839381, 30884.85548919, 32283.32690919],
       [30587.44921028, 30884.85548919, 31795.42772566],
       [30587.44921028, 30396.95630567, 32283.32690919],
       [30587.44921028, 30396.95630567, 31795.42772566],
       [29413.44179992, 30991.58343559, 32481.53595249],
       [29413.44179992, 30961.08973662, 32512.02965146],
       [29382.94810095, 30961.08973662, 32512.02965146],
       [29382.94810095, 30991.58343559, 32512.02965146],
       [29398.19495044, 31037.32398405, 32496.78280198],
       [29489.67598919, 31128.8050228 , 32527.27644279],
       [29413.44179992, 30930.59603765, 32512.02965146],
       [29382.94810095, 30930.5

In [135]:
p = np.array([[29002.849053, 30850.33039364, 32111.48087621]])
dist2base = np.sum((o.baseNodePositions - p)**2., axis=1)
dist2 = np.sum((allPositions - p)**2., axis=1)
print(min(dist2)**0.5, min(dist2base)**0.5)

378.486422148253 478.0905043418064


In [133]:
x = p[:,0]
allx = allPositions[:,0]
d = abs(allx - x)
d2 = (allx - x)**2
print(allx[np.argmin(d)], min(d), min(d2)**0.5)

29367.701251467977 364.85219846797554 364.85219846797554


In [123]:
allx[np.where(np.logical_and(allx > 29000, allx < 30000))]

array([29367.70125147, 29367.70130963, 29367.70130963, ...,
       29855.60043499, 29855.60043499, 29855.60043499])

In [142]:
maxPos = np.max(allPositions, axis=0)
minPos = np.min(allPositions, axis=0)
print(maxPos, minPos)
print(maxPos - minPos)
print(allPositions[np.where(allPositions[:,0] == maxPos[0])])
print(np.where(allPositions[:,0] == maxPos[0]))
print(o.baseNodePositions[np.where(o.baseNodePositions[:,0] == maxPos[0])])


[35222.49145378 35031.99854916 36430.46996915] [25464.50778326 25274.01487865 26672.48629864]
[9757.98367051 9757.98367051 9757.98367051]
[[35222.49145378 30884.85566368 32496.78286014]
 [35222.49145378 30884.85566368 32496.78286014]
 [35222.49145378 30884.85554736 32496.78286014]
 [35222.49145378 30884.85554736 32496.78286014]]
(array([1173, 1174, 1175, 1176], dtype=int64),)
[]


In [34]:
import h5py
import os
import numpy as np

In [28]:
fname = os.path.abspath('/Users/ageller/VISUALIZATIONS/FIREdata/m12i_res7100/snapdir_600/snapshot_600.0.hdf5')
f = h5py.File(fname, 'r')
f['PartType0']['Coordinates'][1][0]

29390.371753126536

In [35]:
x = np.array(f['PartType0']['Coordinates'])

In [50]:
print(np.mean(x, axis=0))
print(np.max(x, axis=0))

[29390.37175313 30974.55955615 32475.00873627]
[29367.70125147 31128.80508096 32527.27650095]
[33574.4958079  36041.93961842 37466.55760875]


In [ ]:
n = 0
count = 0
for i in o.baseNodeIndices:
    if (o.nodes[i]['Nparticles'] > 0):
        #print(i, o.nodes[i]['id'], o.nodes[i]['Nparticles'], len(o.nodes[i]['particles']), o.nodes[i]['x'],o.nodes[i]['xWidth'])
        n += o.nodes[i]['Nparticles']
        count += 1
print(n, count)

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

%matplotlib notebook

In [ ]:
fig = plt.figure(figsize=(10,10))
ax = fig.add_subplot(projection='3d')
ax.set_xlim(-200,200)
ax.set_ylim(-200,200)
ax.set_zlim(-200,200)

n = 0
for i in o.baseNodeIndices:
    if (o.nodes[i]['Nparticles'] > 0 ):
        parts = np.array(o.nodes[i]['particles'])
        x = parts[:,0]
        y = parts[:,1]
        z = parts[:,2]
        ax.scatter(x,y, z)


In [ ]:
#I'd like to check this in Firefly
# - I will try to recreate my previous workflow with per-particle colors with the current version of python