# Attempting to write an octree in python

I want this to work with VERY large data sets that can't be stored fully in memory.  So my procedure will be as follows:
- need to read in line-by-line and clear memory every X MB (or maybe every X particles;can I check memory load in python?)
- go down to nodes with containing N particles
- need to write out tree with node sizes and centers and also ending nodes with actual particles

I will work in the octreeStream.py file.  This is working, though once it has to start reading and writing lots of files, it becomes VERY slow (setting NMemoryMax to be as large as possible will speed things up).

The ultimate goal is to use this within Firefly.  First I create the python code.  Then I will create a simple WebGL utility to use it (hopefully showing more Gaia data than it can handle w/o the octree).  Then we will work on incorporating this into Firefly.

In [2]:
%load_ext autoreload
%autoreload 2

from octreeStream import octreeStream

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [7]:
#I'll use a Gaia data set.  I've already compiled this one from DR2.  For production, I'd want to recompile from EDR3
# WORK/Gaia/GaiaCompiled_RV_TAP.txt
# for some reason this is a space-separated and not comma-separated, but here are the colummns
# 'x', 'y', 'z', 'vx', 'vy', 'vz', 'teff_val', 'phot_g_mean_mag', 'flag'
# I believe flag == 1 if there is no RV; for now all I care about is the x,y,z, position

o = octreeStream('/Users/ageller/WORK/Gaia/GaiaCompiled_RV_TAP.txt', delim = ' ', 
                 NNodeMax = 50000, NMemoryMax = 3e6, Nmax=1e5, verbose=1, minWidth=0.1,
                 path='/Users/ageller/VISUALIZATIONS/octree_threejs_Gaia/WebGL_octreePartition/src/data/junk')

files will be output to: C:\Users\ageller\VISUALIZATIONS\octree_threejs_Gaia\WebGL_octreePartition\src\data\junk


In [8]:
o.compileOctree()

have initial center and size [ -457.4696629   -433.66704784 -1039.13279431] 15557.616459301153
line :  10000
line :  20000
line :  30000
line :  40000
creating child nodes 0 0 50000 15557.616459301153
line :  50000
creating child nodes 1 0_1 50000 7778.808229650576
creating child nodes 16 0_1_8 50000 3889.404114825288
creating child nodes 24 0_1_8_8 50000 1944.702057412644
line :  60000
line :  70000
line :  80000
creating child nodes 28 0_1_8_8_4 50000 972.351028706322
line :  90000
line :  100000
dumping nodes to files ...
randomizing particle order in data files ... 
done


In [9]:
o.checkNodeFiles()

Number of bad files =  0
maximum number of particles in a file =  28960
minimum number of particles in a file =  3


In [10]:
#o.populateAllNodesFromFiles()

Populated octree from files.
 -- total number of particles =  100000
 -- total number of nodes =  41
 -- total number of base nodes =  30


## Testing with hdf5 files

### Gas

In [176]:
o = octreeStream('/Users/ageller/VISUALIZATIONS/FIREdata/m12i_res7100/snapdir_600/snapshot_600.0.hdf5', 
                 h5keyList = ['PartType0', 'Coordinates'],
                 NNodeMax = 50000, NMemoryMax = 5e6, Nmax=1e9, verbose=1, minWidth=1e-4,
                 path='/Users/ageller/VISUALIZATIONS/octree_threejs_Gaia/WebGL_octreePartition/src/data/m12i_res71000/octreeNodes/Gas')

files will be output to: C:\Users\ageller\VISUALIZATIONS\octree_threejs_Gaia\WebGL_octreePartition\src\data\m12i_res71000\octreeNodes\Gas


In [ ]:
o.compileOctree()

calculating center and size ... 
have initial center and size [29367.70125147 31128.80508096 32527.27650095] 15612.77387281969
line :  10000
line :  20000
line :  30000
line :  40000
creating child nodes 0 50000 15612.77387281969
line :  50000
line :  60000
line :  70000
line :  80000
line :  90000
line :  100000
line :  110000
line :  120000
creating child nodes 07 50000 7806.386936409845
creating child nodes 072 50001 3903.1934682049223
line :  130000
creating child nodes 0722 50000 1951.5967341024611
line :  140000
line :  150000
line :  160000
line :  170000
creating child nodes 07221 50000 975.7983670512306
line :  180000
line :  190000
line :  200000
line :  210000
line :  220000
line :  230000
creating child nodes 07222 50000 975.7983670512306
creating child nodes 072222 50001 487.8991835256153
creating child nodes 0722222 50002 243.94959176280764
creating child nodes 07222224 50003 121.97479588140382
creating child nodes 072222242 50000 60.98739794070191
line :  240000
line :  

In [ ]:
o.compileOctree(inputFile='/Users/ageller/VISUALIZATIONS/FIREdata/m12i_res7100/snapdir_600/snapshot_600.1.hdf5', append=True)

In [ ]:
o.compileOctree(inputFile='/Users/ageller/VISUALIZATIONS/FIREdata/m12i_res7100/snapdir_600/snapshot_600.2.hdf5', append=True)

In [ ]:
o.compileOctree(inputFile='/Users/ageller/VISUALIZATIONS/FIREdata/m12i_res7100/snapdir_600/snapshot_600.3.hdf5', append=True)

In [ ]:
o.checkNodeFiles()

### Stars

In [ ]:
o = octreeStream('/Users/ageller/VISUALIZATIONS/FIREdata/m12i_res7100/snapdir_600/snapshot_600.0.hdf5', 
                 h5keyList = ['PartType4', 'Coordinates'],
                 NNodeMax = 50000, NMemoryMax = 5e6, Nmax=1e9, verbose=1, minWidth=1e-4,
                 path='/Users/ageller/VISUALIZATIONS/octree_threejs_Gaia/WebGL_octreePartition/src/data/m12i_res71000/octreeNodes/Stars')

In [ ]:
o.compileOctree(inputFile='/Users/ageller/VISUALIZATIONS/FIREdata/m12i_res7100/snapdir_600/snapshot_600.1.hdf5', append=True)

In [ ]:
o.compileOctree(inputFile='/Users/ageller/VISUALIZATIONS/FIREdata/m12i_res7100/snapdir_600/snapshot_600.2.hdf5', append=True)

In [ ]:
o.compileOctree(inputFile='/Users/ageller/VISUALIZATIONS/FIREdata/m12i_res7100/snapdir_600/snapshot_600.3.hdf5', append=True)

In [ ]:
o.checkNodeFiles()

### HRDM

In [ ]:
o = octreeStream('/Users/ageller/VISUALIZATIONS/FIREdata/m12i_res7100/snapdir_600/snapshot_600.0.hdf5', 
                 h5keyList = ['PartType1', 'Coordinates'],
                 NNodeMax = 50000, NMemoryMax = 5e6, Nmax=1e9, verbose=1, minWidth=1e-4,
                 path='/Users/ageller/VISUALIZATIONS/octree_threejs_Gaia/WebGL_octreePartition/src/data/m12i_res71000/octreeNodes/HRDM')

In [ ]:
o.compileOctree(inputFile='/Users/ageller/VISUALIZATIONS/FIREdata/m12i_res7100/snapdir_600/snapshot_600.1.hdf5', append=True)

In [ ]:
o.compileOctree(inputFile='/Users/ageller/VISUALIZATIONS/FIREdata/m12i_res7100/snapdir_600/snapshot_600.2.hdf5', append=True)

In [ ]:
o.compileOctree(inputFile='/Users/ageller/VISUALIZATIONS/FIREdata/m12i_res7100/snapdir_600/snapshot_600.3.hdf5', append=True)

In [ ]:
o.checkNodeFiles()

### LRDM

In [ ]:
o = octreeStream('/Users/ageller/VISUALIZATIONS/FIREdata/m12i_res7100/snapdir_600/snapshot_600.0.hdf5', 
                 h5keyList = ['PartType2', 'Coordinates'],
                 NNodeMax = 50000, NMemoryMax = 5e6, Nmax=1e9, verbose=1, minWidth=1e-4,
                 path='/Users/ageller/VISUALIZATIONS/octree_threejs_Gaia/WebGL_octreePartition/src/data/m12i_res71000/octreeNodes/LRDM')

In [ ]:
o.compileOctree(inputFile='/Users/ageller/VISUALIZATIONS/FIREdata/m12i_res7100/snapdir_600/snapshot_600.1.hdf5', append=True)

In [ ]:
o.compileOctree(inputFile='/Users/ageller/VISUALIZATIONS/FIREdata/m12i_res7100/snapdir_600/snapshot_600.2.hdf5', append=True)

In [ ]:
o.compileOctree(inputFile='/Users/ageller/VISUALIZATIONS/FIREdata/m12i_res7100/snapdir_600/snapshot_600.3.hdf5', append=True)

In [ ]:
o.checkNodeFiles()

In [ ]:
#o.populateAllNodesFromFiles()

In [100]:
o.checkNodeParticles(iden='0722222468888888888888888888')

checking node...
width =  0.00011632423008098967
center =  [29367.70130963009, 30945.842945297733, 32405.301763230585]
mean particle position =  [28117.75403463 29846.04872256 31358.68751193]
max particle position =  [29002.849053   30850.33039364 32111.48087621]
min particle position =  [28005.81009505 29706.78577699 31173.12291594]
max distance for particle positions =  [ 997.03895795 1143.54461666  938.35796027]


In [101]:
import numpy as np

In [105]:
for i,n in enumerate(o.nodes):
    if (i == 0):
        allPositions = np.array([[n['x'], n['y'], n['z']]])
    else:
        allPositions = np.append(allPositions, [[n['x'], n['y'], n['z']]], axis=0)
print(allPositions)

[[29367.70125147 31128.80508096 32527.27650095]
 [33270.89471967 35031.99854916 36430.46996915]
 [25464.50778326 35031.99854916 36430.46996915]
 ...
 [29367.70130963 30884.85566368 32496.78286014]
 [29367.70142595 30884.85554736 32496.78286014]
 [29367.70130963 30884.85554736 32496.78286014]]


In [104]:
o.baseNodePositions

array([[33270.89471967, 27225.61161275, 36430.46996915],
       [25464.50778326, 27225.61161275, 36430.46996915],
       [32295.09635262, 30153.00671391, 31551.4781339 ],
       [31075.34839381, 30396.95630567, 32283.32690919],
       [31075.34839381, 30396.95630567, 31795.42772566],
       [31075.34839381, 30884.85548919, 31795.42772566],
       [31075.34839381, 30884.85548919, 32283.32690919],
       [30587.44921028, 30884.85548919, 31795.42772566],
       [30587.44921028, 30396.95630567, 32283.32690919],
       [30587.44921028, 30396.95630567, 31795.42772566],
       [29413.44179992, 30991.58343559, 32481.53595249],
       [29413.44179992, 30961.08973662, 32512.02965146],
       [29382.94810095, 30961.08973662, 32512.02965146],
       [29382.94810095, 30991.58343559, 32512.02965146],
       [29398.19495044, 31037.32398405, 32496.78280198],
       [29489.67598919, 31128.8050228 , 32527.27644279],
       [29413.44179992, 30930.59603765, 32512.02965146],
       [29382.94810095, 30930.5

In [135]:
p = np.array([[29002.849053, 30850.33039364, 32111.48087621]])
dist2base = np.sum((o.baseNodePositions - p)**2., axis=1)
dist2 = np.sum((allPositions - p)**2., axis=1)
print(min(dist2)**0.5, min(dist2base)**0.5)

378.486422148253 478.0905043418064


In [133]:
x = p[:,0]
allx = allPositions[:,0]
d = abs(allx - x)
d2 = (allx - x)**2
print(allx[np.argmin(d)], min(d), min(d2)**0.5)

29367.701251467977 364.85219846797554 364.85219846797554


In [123]:
allx[np.where(np.logical_and(allx > 29000, allx < 30000))]

array([29367.70125147, 29367.70130963, 29367.70130963, ...,
       29855.60043499, 29855.60043499, 29855.60043499])

In [142]:
maxPos = np.max(allPositions, axis=0)
minPos = np.min(allPositions, axis=0)
print(maxPos, minPos)
print(maxPos - minPos)
print(allPositions[np.where(allPositions[:,0] == maxPos[0])])
print(np.where(allPositions[:,0] == maxPos[0]))
print(o.baseNodePositions[np.where(o.baseNodePositions[:,0] == maxPos[0])])


[35222.49145378 35031.99854916 36430.46996915] [25464.50778326 25274.01487865 26672.48629864]
[9757.98367051 9757.98367051 9757.98367051]
[[35222.49145378 30884.85566368 32496.78286014]
 [35222.49145378 30884.85566368 32496.78286014]
 [35222.49145378 30884.85554736 32496.78286014]
 [35222.49145378 30884.85554736 32496.78286014]]
(array([1173, 1174, 1175, 1176], dtype=int64),)
[]


In [34]:
import h5py
import os
import numpy as np

In [28]:
fname = os.path.abspath('/Users/ageller/VISUALIZATIONS/FIREdata/m12i_res7100/snapdir_600/snapshot_600.0.hdf5')
f = h5py.File(fname, 'r')
f['PartType0']['Coordinates'][1][0]

29390.371753126536

In [35]:
x = np.array(f['PartType0']['Coordinates'])

In [50]:
print(np.mean(x, axis=0))
print(np.max(x, axis=0))

[29390.37175313 30974.55955615 32475.00873627]
[29367.70125147 31128.80508096 32527.27650095]
[33574.4958079  36041.93961842 37466.55760875]


In [ ]:
n = 0
count = 0
for i in o.baseNodeIndices:
    if (o.nodes[i]['Nparticles'] > 0):
        #print(i, o.nodes[i]['id'], o.nodes[i]['Nparticles'], len(o.nodes[i]['particles']), o.nodes[i]['x'],o.nodes[i]['xWidth'])
        n += o.nodes[i]['Nparticles']
        count += 1
print(n, count)

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

%matplotlib notebook

In [ ]:
fig = plt.figure(figsize=(10,10))
ax = fig.add_subplot(projection='3d')
ax.set_xlim(-200,200)
ax.set_ylim(-200,200)
ax.set_zlim(-200,200)

n = 0
for i in o.baseNodeIndices:
    if (o.nodes[i]['Nparticles'] > 0 ):
        parts = np.array(o.nodes[i]['particles'])
        x = parts[:,0]
        y = parts[:,1]
        z = parts[:,2]
        ax.scatter(x,y, z)


In [ ]:
#I'd like to check this in Firefly
# - I will try to recreate my previous workflow with per-particle colors with the current version of python